const Products = [
		{
			id: '1',
			type:'combo',
			name: 'Combo Burger',
			description: 'Simple but jucy burger. Choose your toppings.',
			price: 9.99,
			img:'./images/products/burger',
		},
		{
			id: '2',
			type:'combo',
			name: 'Combo Double Burger',
			description: 'Double jucy delicious burger. Choose your toppings.',
			price: 10.99,
			img:'./images/products/double-burger',
		},
		{
			id: '3',
			type:'combo',
			name: 'Combo Burger + Cheese',
			description: 'What’s a burger without cheese? Choose your toppings.',
			price: 11.99,
			img:'./images/products/burger-cheese',
		},
		{
			id: '4',
			type:'combo',
			name: 'Combo Double Burger + Cheese',
			description: 'What’s a burger without melted delicious DOUBLE cheese?',
			price: 15.49,
			img:'./images/products/double-burger-cheese',
		},
		{
			id: '5',
			type:'burgers',
			name: 'Burger',
			description: 'Simple but jucy burger. Choose your toppings.',
			price: 6.25,
			img:'./images/products/burger',
		},
		{
			id: '6',
			type:'burgers',
			name: 'Double Burger',
			description: 'Double jucy delicious burger. Choose your toppings.',
			price: 8.49,
			img:'./images/products/double-burger',
		},
		{
			id: '7',
			type:'burgers',
			name: 'Burger + Cheese',
			description: 'What’s a burger without cheese? Choose your toppings.',
			price: 9.00,
			img:'./images/products/burger-cheese',
		},
		{
			id: '8',
			type:'burgers',
			name: 'Double Burger + Cheese',
			description: 'What’s a burger without melted delicious DOUBLE cheese?',
			price: 13.00,
			img:'./images/products/double-burger-cheese',
		},
		{
			id: '9',
			type:'other',
			name: 'Fires',
			description: 'Crunchy unique fries.',
			price: 3.49,
			img:'./images/products/fries',
		},
		{
			id: '10',
			type:'other',
			name: 'Soda',
			description: 'Accompany your burger with a soda.',
			price: 1.00,
			img:'./images/products/soda',
		},

]

export default Products